### ISSUE TITLE
Create New Account

### ISSUE THREAD

**Issue by GoldenSharkStudio** [Nethereum/Unity3dSimpleSampleNet461#3]
Hi, I'm having difficulties trying to create a new account for a testnet network (BSC), I have the url, but I can't generate a new account using web3 and I can't find how in the documentation, could you give me a light? @juanfranblanco

**Comment by GoldenSharkStudio** [comment]
This is the example code for the BSC with web3:
https://docs.binance.org/smart-chain/developer/create-wallet.html#full-example

This is how i tried to do with Nethereum:
https://docs.nethereum.com/en/latest/nethereum-creating-a-new-account-using-geth/

**Comment by juanfranblanco** [comment]
@GoldenSharkStudio you should not use geth to generate an account, that is specific to using that client.
